
## Tasks to be run _on the swarm manager_
namespace :network do
  task :create do
    sh "docker network create --attachable --driver=overlay lazycache"
  end
end

namespace :lazycache do
  task :deploy do
    sh "docker service create --name lazycache_nocache --network lazycache -p 8080 amarburg/lazycache_nocache_ursine:latest"
  end
end

namespace :worker do
  task :deploy do
    sh "docker service create --env-file prod.env --name worker "\
          "--constraint node.role!=manager --network lazycache "\
          "--mount type=volume,volume-opt=o=addr=swarm-manager,volume-opt=device=:/home/amarburg/CamHD_motion_metadata,volume-opt=type=nfs,source=camhd_motion_metadata_by_nfs,target=/output/CamHD_motion_metadata,volume-nocopy " \
          "amarburg/camhd_motion_analysis_rq_worker:latest --log INFO"
  end
end



## Tasks for setting up the swarm
namespace :gcloud do

  task :ssh do
    sh "gcloud --project=camhd-motion-analysis-swarm compute ssh swarm-manager "
  end

  task :manager do
    sh "docker-machine create swarm-manager -d google " \
                " --google-machine-type g1-small "\
                " --google-zone us-central1-a "\
                " --google-tags swarm-cluster "\
                " --google-project camhd-motion-analysis-swarm " \
                " --swarm-master " \
                " --google-tags redis-tcp-6379" \
                " --metadata-from-file startup-script=swarm-manager-startup-script.sh"
  end

  instance_version = "rev0"
  instance_name   = "swarm-coreos-alpha-n1-highcpu-8"
  instance_fullname = [instance_name, instance_version].join('-')


  namespace :swarm do

    task :template do
      sh "gcloud compute instance-templates create #{instance_fullname} \
                  --machine-type n1-highcpu-8 \
                  --preemptible \
                  --image-family coreos-alpha \
                  --image-project coreos-cloud \
                  --boot-disk-size 10GB \
                  --metadata-from-file user-data=swarm-worker-cloud-init"
    end

    task :deploy do
      sh "gcloud compute instance-groups managed create worker-alpha-swarm \
                  --template #{instance_fullname} \
                  --base-instance-name #{instance_name} \
                  --size 1 \
                  --zone us-central1-a"
    end

  end

end
