
require 'bundler'
require 'dotenv'


namespace :network do
  task :create do
    sh "docker network create --attachable --driver=overlay lazycache"
  end
end


namespace :lazycache do
  task :deploy do
    sh "docker service create --name lazycache_nocache --network lazycache -p 8080 amarburg/lazycache_nocache_ursine:latest"
  end
end


namespace :worker do
  task :deploy do
    sh "docker service create --env-file prod.env --name worker "\
          "--network lazycache "\
          "--mount type=volume,volume-opt=o=addr=192.168.13.110,volume-opt=device=:/mnt/zvol1/users/aaron/camhd_analysis/CamHD_motion_metadata/,volume-opt=type=nfs,source=camhd_motion_metadata_by_nfs,target=/output/CamHD_motion_metadata,volume-nocopy " \
          "amarburg/camhd_motion_analysis_rq_worker:latest --log INFO"
  end
end


task :inject do
  Dotenv.load('prod.env')
  sh "docker run --rm --env-file prod.env "\
          " --entrypoint python3 "\
          " --network lazycache" \
          " --volume camhd_motion_metadata_by_nfs:/output/CamHD_motion_metadata" \
          " amarburg/camhd_motion_analysis_rq_worker:latest"\
          " /code/camhd_motion_analysis/python/rq_client.py " \
          " --threads 16 " \
          " --log INFO " \
          " --lazycache-url http://lazycache_nocache:8080/v1/org/oceanobservatories/rawdata/files" \
          " --output-dir /output/CamHD_motion_metadata"\
          " /RS03ASHS/PN03B/06-CAMHDA301/2016/02/"
end
